version: "3"
services:
  # zookeeper:
  #   image: wurstmeister/zookeeper
  # kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: localhost
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  # redis:
  #   image: redis
  #   container_name: cache
  #   ports:
  #     - "6379:6379"
  dockerhost:
    image: alpine
    container_name: fworkhost
    entrypoint: /bin/sh -c "tail -f /dev/null"
    network_mode: host
  proxy:
    image: nginx:alpine
    container_name: fworkproxy
    links:
      - dockerhost:dockerhost
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      # - "./nginx/developer.conf:/etc/nginx/conf.d/developer.conf:ro"
      # - "./nginx/admin.conf:/etc/nginx/conf.d/admin.conf:ro"
